name: Generate Tetrass

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: git diff --exit-code action/index.mjs

      - name: Generate SVGs
        uses: ./action
        with:
          github_user_name: ${{ github.actor }}
          outputs: |
            img/tetrass.svg
            img/tetrass-dark.svg?palette=github-dark

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Tetrass SVG"
          file_pattern: "img/*.svg"
